FROM node:18.3.0

WORKDIR /

COPY . . 

RUN yarn install;

RUN npm install;

ENV HOST="35.229.209.81"
ENV USER="admin"
ENV PASSWORD="cloud123"
ENV DB="STADIUM"
ENV GENERATE_SOURCEMAP=false
ENV NODE_OPTIONS=--max-old-space-size=16384

CMD ["yarn", "dev"]

